In [5]:
import sys
sys.path.insert(0, '..')

from sequence_encoders import RollingMasker

In [70]:
sequence = "AATGTGTGT"
motif = {'ATG':1,
         'TGT':2}

In [71]:
masker = RollingMasker(mask_stride=3)
x_batch, y_masked_batch, y_batch, mask_batch, motif_mask_batch = masker(sequence, motif)

In [72]:
print([*sequence])
x_batch[0]

['A', 'A', 'T', 'G', 'T', 'G', 'T', 'G', 'T']


tensor([[0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 1., 0.],
        [0., 0., 1., 0., 1., 0., 0., 0., 1.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [73]:
motif_mask_batch

tensor([[0., 1., 2., 2., 2., 0., 2., 2., 2.],
        [0., 1., 2., 2., 2., 0., 2., 2., 2.],
        [0., 1., 2., 2., 2., 0., 2., 2., 2.]], dtype=torch.float64)

In [60]:
print([*sequence])
y_masked_batch

['T', 'A', 'T', 'G', 'T', 'A', 'C', 'C', 'N', 'N']


tensor([[   3, -100, -100,    2, -100, -100,    1, -100, -100,    4],
        [-100,    0, -100, -100,    3, -100, -100,    1, -100, -100],
        [-100, -100,    3, -100, -100,    0, -100, -100,    4, -100]])

In [61]:
y_batch

tensor([[3, 0, 3, 2, 3, 0, 1, 1, 4, 4],
        [3, 0, 3, 2, 3, 0, 1, 1, 4, 4],
        [3, 0, 3, 2, 3, 0, 1, 1, 4, 4]])